### ISSUE TITLE
Doesn't print text & images using imp005 on Honeywell Datamax Workstation printer

### ISSUE THREAD

**Issue by shubh261096** [electricimp/examples#25]
Printing text and images via imp005 on Brother QL1110NWB and Honeywell Datamax workstaion label printer is not working.

**Comment by hfiennes** [comment]
None of these examples are intended to drive those printers. You would have to write your own drivers for that.

**Comment by shubh261096** [comment]
I am successfully able to print text but Image is not getting printed. Can you please help me with it?

**Comment by betzrhodes** [comment]
As Hugo stated, we have no printer drivers for Honeywell Datamax printers, so none of the examples in this repository will show how to print using this printer. That being said, some printers may share some command formatting, so while printing text the driver appeared to work. However for a printer to work properly it need its own driver. To write a driver you will need a programmers guide or commands manual for the exact printer you are working with. That document will outline the commands you need to send to make your printer work properly. You will then need to write the squirrel code to execute those commands. The only printer we have a driver for is the Brother QL720NW, and in its current release it only supports text and bar codes - no images. Please feel free to use that as a reference on how to write a driver in squirrel.

**Comment by betzrhodes** [comment]
Closing this issue since we have no plans for writing a printer driver for the Honeywell Datamax printer.
